In [1]:
# sum function expressed as an inner product
sum_fn(x) = ones(length(x))'x

sum_fn (generic function with 1 method)

In [2]:
sum_fn([1, 2, 3, 4, 5])

15.0

In [3]:
# avg function expressed as an inner product
avg(x) = fill(1/length(x), length(x))'x

avg (generic function with 1 method)

In [4]:
avg([1, 2, 3])

2.0

In [24]:
function unit_vector_builder(index, n_elements)
    if index <= n_elements
        output = zeros(n_elements)
        output[index] = 1
        return output
    end
end

unit_vector_builder (generic function with 1 method)

In [25]:
unit_vector_builder(2, 4)

4-element Array{Float64,1}:
 0.0
 1.0
 0.0
 0.0

In [27]:
# The . operator broadcasts any function or operator onto an array
a = [1, 2, 3]
b = [3, 2, 1]

a .== b

3-element BitArray{1}:
 0
 1
 0

In [28]:
f(x) = x + 1

f.(a)

3-element Array{Int64,1}:
 2
 3
 4

In [35]:
a = [3, 4, 5, 6, 7, 8]
b = [4, 3, 1, 2, 3, 4]
b./a # element-wise division

6-element Array{Float64,1}:
 1.3333333333333333
 0.75
 0.2
 0.3333333333333333
 0.42857142857142855
 0.5